

name: Postman


on:
  
  push:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
        
        - name: repo checkout
          uses: actions/checkout@v4
        
          
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
              node-version: '18'
        
          
        - name: install newman
          run: npm install -g newman
        
          
        - name: Run postman test 
          run: newman run postman_tests/Books.postman_collection.json -e postman_tests/test.postman_environment.json
